site_name: Genshin 小说集
site_author: Genshin
site_url: https://Julia-1994.github.io/
repo_name: Julia-1994/Julia-1994.github.io
repo_url: https://github.com/Julia-1994/Julia-1994.github.io

docs_dir: ./docs

theme:
    name: material
    palette:
        primary: "orange"

extra:
  search:
    language: 'jp'

nav:
    - 说明: 'index.md'

    - 图集:
        - 'Amber': 'photo/Amber.md'
        - 'Barbara': 'photo/Barbara.md'
        - 'Jane': 'photo/Jane.md'
        - 'KamisatoAyaka': 'photo/KamisatoAyaka.md'
        - 'Keqing': 'photo/Keqing.md'
        - 'Noelle': 'photo/Noelle.md'
        - 'Xiaogong': 'photo/Xiaogong.md'

    - 安柏:
        - '原神同人文——安柏': 'Amber/原神同人文——安柏.md'
        - '安柏-在时间长河中迷茫的我们': 'Amber/安柏-在时间长河中迷茫的我们.md'
        - '安柏与优菈的窒息游戏': 'Amber/安柏与优菈的窒息游戏.md'
        - '安柏与空与约定的诗': 'Amber/安柏与空与约定的诗.md'
        - '异世发情期': 'Amber/异世发情期.md'
        - '最后的侦察骑士': 'Amber/最后的侦察骑士.md'
        - '轻松拿下侦查骑士': 'Amber/轻松拿下侦查骑士.md'

    - 诺艾尔:
        - '假如说诺艾尔是病娇': 'Noelle/假如说诺艾尔是病娇.md'
        - '原神同人诺艾尔': 'Noelle/原神同人诺艾尔.md'
        - '名为诺艾尔的血色玫瑰': 'Noelle/名为诺艾尔的血色玫瑰.md'
        - '当诺艾尔怀上了旅行者的小宝宝': 'Noelle/当诺艾尔怀上了旅行者的小宝宝.md'
        - '当诺艾尔进入了需要被不断满足的时期': 'Noelle/当诺艾尔进入了需要被不断满足的时期.md'
        - '诺艾尔-前辈这是要': 'Noelle/诺艾尔-前辈这是要.md'
        - '诺艾尔-这段感情就从这里开始吧': 'Noelle/诺艾尔-这段感情就从这里开始吧.md'
        - '诺艾尔的留恋': 'Noelle/诺艾尔的留恋.md'

    - 芭芭拉:
        - '芭芭拉和琴': 'Barbara/芭芭拉和琴.md'
        - '芭芭拉小姐的气球之夜': 'Barbara/芭芭拉小姐的气球之夜.md'
        - '蒙德酒业摧毁计划': 'Barbara/蒙德酒业摧毁计划.md'

    - 神里绫华:
        - '当旅行者让神里绫华独守空房一个月会怎么样': 'Kamisato Ayaka/当旅行者让神里绫华独守空房一个月会怎么样.md'
        - '当神里绫华想为旅行者暖床': 'Kamisato Ayaka/当神里绫华想为旅行者暖床.md'
        - '当神里绫华进入了需要被不断满足的时期': 'Kamisato Ayaka/当神里绫华进入了需要被不断满足的时期.md'
        - '白鹭折翼水囿浊，兄妹竟相合': 'Kamisato Ayaka/白鹭折翼水囿浊，兄妹竟相合.md'
        - '神里-发生在社奉行的那些事': 'Kamisato Ayaka/神里-发生在社奉行的那些事.md'
        - '神里-海灯节祭典那一夜': 'Kamisato Ayaka/神里-海灯节祭典那一夜.md'
        - '神里绫华-逐月佳节-食与山河': 'Kamisato Ayaka/神里绫华-逐月佳节-食与山河.md'
        - '神里绫华簌簌红叶送君去': 'Kamisato Ayaka/神里绫华簌簌红叶送君去.md'
        - '笼中鸟-稻妻篇': 'Kamisato Ayaka/笼中鸟-稻妻篇.md'
        - '笼中鸟': 'Kamisato Ayaka/笼中鸟.md'
        - '绫华大小姐怀上了空的孩子': 'Kamisato Ayaka/绫华大小姐怀上了空的孩子.md'

    - 丽萨:
        - '丽莎姐姐俘获我': 'Lisa/丽莎姐姐俘获我.md'
        - '丽莎姐姐的特别教程': 'Lisa/丽莎姐姐的特别教程.md'
        - '丽莎的惩罚': 'Lisa/丽莎的惩罚.md'
        - '沙漏星象': 'Lisa/沙漏星象.md'
        - '跟我进屋': 'Lisa/跟我进屋.md'
        - '闯进盛夏的紫蔷薇': 'Lisa/闯进盛夏的紫蔷薇.md'

    - 可以色色:
        - '00 前言': 'Genshin-hot/00 前言.md'
        - '01 原神 图书馆奇妙夜': 'Genshin-hot/01 原神 图书馆奇妙夜.md'
        - '02 荣誉骑士的恋爱训练': 'Genshin-hot/02 荣誉骑士的恋爱训练.md'
        - '03 提瓦特之冬': 'Genshin-hot/03 提瓦特之冬.md'
        - '04 观赏鱼交配指南': 'Genshin-hot/04 观赏鱼交配指南.md'
        - '05 天权与漆黑魔剑': 'Genshin-hot/05 天权与漆黑魔剑.md'
        - '06 富婆 饿饿 饭饭': 'Genshin-hot/06 富婆 饿饿 饭饭.md'
        - '07 黄金王兽的计划和海祇岛与鸣神岛的冲突': 'Genshin-hot/07 黄金王兽的计划和海祇岛与鸣神岛的冲突.md'
        - '08 与诺艾尔的温情时光': 'Genshin-hot/08 与诺艾尔的温情时光.md'
        - '09 一个小结尾': 'Genshin-hot/09 一个小结尾.md'
        - '10 凝光的弱点': 'Genshin-hot/10 凝光的弱点.md'
        - '11 关于我ntr了优菈的那些事': 'Genshin-hot/11 关于我ntr了优菈的那些事.md'
        - '12 从调情到精液浴的派蒙性爱指南': 'Genshin-hot/12 从调情到精液浴的派蒙性爱指南.md'
        - '13 被八重神子和影联合压榨的旅行者': 'Genshin-hot/13 被八重神子和影联合压榨的旅行者.md'
        - '14 与申鹤的性交初体验': 'Genshin-hot/14 与申鹤的性交初体验.md'
        - '15 来自丽莎姐姐的特别疗法': 'Genshin-hot/15 来自丽莎姐姐的特别疗法.md'
        - '16 丽莎姐姐的特别教程': 'Genshin-hot/16 丽莎姐姐的特别教程.md'
        - '17 凝光与北斗的联合性行为': 'Genshin-hot/17 凝光与北斗的联合性行为.md'
        - '18 夏祭女王的私密时光': 'Genshin-hot/18 夏祭女王的私密时光.md'
        - '19 大家都是安柏的翅膀': 'Genshin-hot/19 大家都是安柏的翅膀.md'
        - '20 代理团长的放松方式': 'Genshin-hot/20 代理团长的放松方式.md'
        - '21 与心海的刑邢涩涩': 'Genshin-hot/21 与心海的刑邢涩涩.md'
        - '22 与水之龙王的刑邢涩涩': 'Genshin-hot/22 与水之龙王的刑邢涩涩.md'
        - '23 之前说好的安朵斯——珊瑚宫心海的属性': 'Genshin-hot/23 之前说好的安朵斯——珊瑚宫心海的属性.md'
        - '24 被传统观念束缚的璃月小律师': 'Genshin-hot/24 被传统观念束缚的璃月小律师.md'

    - 其他:
        - '烟绯-烟绯之眠': 'others/烟绯-烟绯之眠.md'
        - '琴-当琴怀上了旅行者的小宝宝': 'others/琴-当琴怀上了旅行者的小宝宝.md'
        - '神子-你今晚逃不掉了乖乖的躺在床上吧': 'others/神子-你今晚逃不掉了乖乖的躺在床上吧.md'
        - '神子-八重神子的恶作剧': 'others/神子-八重神子的恶作剧.md'
        - '荧-孕母征途': 'others/荧-孕母征途.md'
        - '阿贝多-水元素的实验': 'others/阿贝多-水元素的实验.md'
        - '胡桃-请速来拜会堂主想你': 'Hutao/胡桃-请速来拜会堂主想你.md'
        - '胡桃和氪金过多的少女': 'Hutao/胡桃和氪金过多的少女.md'
        - '当刻晴怀上了旅行者的小宝宝': 'Keqing/当刻晴怀上了旅行者的小宝宝.md'
        - '椰羊的正确打开方式-刻晴甘雨': 'Keqing/椰羊的正确打开方式-刻晴甘雨.md'
        - '凝光-星耀绝云间': 'Ningguang/凝光-星耀绝云间.md'
        - '凝光-群星皆暗，天权玉崩': 'Ningguang/凝光-群星皆暗，天权玉崩.md'
        - '行秋-天动万象': 'Xingqiu/行秋-天动万象.md'
